/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BlockLabRuntimeModule extends AbstractBlockLabRuntimeModule {
}
