/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BlockLabStandaloneSetup extends BlockLabStandaloneSetupGenerated {

	public static void doSetup() {
		new BlockLabStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
