/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt.tests

import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
class BlockLabParsingTest {
	
	@Test
	def void loadModel() {
		Assertions.assertTrue(true)
	}
}
