/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt.web;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.eclipse.xtext.util.DisposableRegistry;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;
import org.eclipse.xtext.web.servlet.XtextServlet;

import com.google.inject.Injector;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
@WebServlet(name = "XtextServices", urlPatterns = "/xtext-service/*")
public class BlockLabServlet extends XtextServlet {
	
	private static final long serialVersionUID = 1L;
	
	DisposableRegistry disposableRegistry;
	
	public void init() throws ServletException {
		super.init();
		IResourceBaseProvider resourceBaseProvider = new ResourceBaseProviderImpl("./test-files");
		Injector injector = new BlockLabWebSetup(resourceBaseProvider).createInjectorAndDoEMFRegistration();
		this.disposableRegistry = injector.getInstance(DisposableRegistry.class);
	}
	
	@Override
	protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// resp.addHeader("Access-Control-Allow-Origin", "*");
		// resp.addHeader("Access-Control-Allow-Credentials", "true");
		// resp.addHeader("Access-Control-Allow-Methods", "*");
		// resp.addHeader("Access-Control-Allow-Headers", "Content-Type");
		super.doGet(req, resp);
	}

	public void destroy() {
		if (disposableRegistry != null) {
			disposableRegistry.dispose();
			disposableRegistry = null;
		}
		super.destroy();
	}
	
}
