/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt.web;

import org.eclipse.xtext.web.server.generator.IContentTypeProvider;
import org.eclipse.xtext.web.server.model.IWebResourceSetProvider;
import org.eclipse.xtext.web.server.persistence.FileResourceHandler;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import org.zhaw.husmaret.mt.web.resource.DslContentTypeProvider;
import org.zhaw.husmaret.mt.web.resource.DslResourceSetProvider;

import com.google.inject.Binder;

/**
 * Use this class to register additional components to be used within the web application.
 */
public class BlockLabWebModule extends AbstractBlockLabWebModule {
	
	private IResourceBaseProvider resourceBaseProvider;

	@Override
	public Class<? extends IContentTypeProvider> bindIContentTypeProvider() {
		return DslContentTypeProvider.class;
	}

	public Class<? extends IWebResourceSetProvider> bindIWebResourceSetProvider() {
		return DslResourceSetProvider.class;
	}

	public void configureResourceBaseProvider(Binder binder) {
		if (resourceBaseProvider != null) {
			binder.bind(IResourceBaseProvider.class).toInstance(resourceBaseProvider);
		}
	}

	public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
		return FileResourceHandler.class;
	}

	public BlockLabWebModule(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}
	
}
