/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt.web;

import org.eclipse.xtext.util.Modules2;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.zhaw.husmaret.mt.BlockLabRuntimeModule;
import org.zhaw.husmaret.mt.BlockLabStandaloneSetup;
import org.zhaw.husmaret.mt.ide.BlockLabIdeModule;

import com.google.inject.Guice;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class BlockLabWebSetup extends BlockLabStandaloneSetup {
	
	private IResourceBaseProvider resourceBaseProvider;

	public BlockLabWebSetup(IResourceBaseProvider resourceBaseProvider) {
		this.resourceBaseProvider = resourceBaseProvider;
	}
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BlockLabRuntimeModule(), new BlockLabIdeModule(), new BlockLabWebModule(this.resourceBaseProvider)));
	}
	
}
