/*
 * generated by Xtext 2.30.0
 */
package org.zhaw.husmaret.mt.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.zhaw.husmaret.mt.BlockLabRuntimeModule;
import org.zhaw.husmaret.mt.BlockLabStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BlockLabIdeSetup extends BlockLabStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BlockLabRuntimeModule(), new BlockLabIdeModule()));
	}
	
}
